### ISSUE TITLE
GivEnergy AIO Support?

### ISSUE THREAD

**Issue by pbyrne-ms** [VeniVidiVici/givtcp-power-flow-card#166]
Is it possible to add support for the GivEnergy All-In-One system to this power flow card?
Currently, the card requires at least one battery to be declared in the settings, but due to the nature of the AIO, it only presents itself as an Inverter (via GivTCP), it does not have a separate standalone battery device/entity.
Although it does provide all the individual/equivalent battery data entities regarding power and energy in/out, SOC etc. 
Is it possible to override the card's normal auto-finding mechanism via the serial number "sensor.givtcp....._serial_number" method and manually enter the entities needed to operate the card?

For example, my system has the following entities available

```
1. sensor.givtcp_<serial>_battery_to_grid
2. sensor.givtcp_<serial>_battery_to_house
3. sensor.givtcp_<serial>_grid_to_battery
4. sensor.givtcp_<serial>_solar_to_battery
5. sensor.givtcp_<serial>_battery_power
6. sensor.givtcp_<serial>_soc
7. (and many more...)
```

**Comment by VeniVidiVici** [comment]
Yes I can do that, I'll look at getting it added over the next week or two

**Comment by adamdoran** [comment]
Also interested in this, and willing to test. Cheers.

**Comment by VeniVidiVici** [comment]
added AIO support in in 0.6.0

**Comment by adamdoran** [comment]
Thanks, working perfectly!
