### ISSUE TITLE
Battery arrow always shows outwards (discharging) even when charging

### ISSUE THREAD

**Issue by theblackcat9** [VeniVidiVici/givtcp-power-flow-card#196]
I think this power flow chart is great and I've got it set-up how I want it with the cross layout and "hide inactive flows" on v0.6.1. The one minor thing that would be nice if it was fixed is the arrow on the battery entity always points outwards whether it is discharging or charging.  Attached is a screenshot when the battery is charging from solar.
![Screenshot_20240117-121612-850](https://github.com/VeniVidiVici/givtcp-power-flow-card/assets/143742549/1b945e25-1a86-4286-9caa-992ba6e6f1fa)

**Comment by VeniVidiVici** [comment]
this has been fixed in v0.6.2
