### ISSUE TITLE
Multi Invertor options not showing

### ISSUE THREAD

**Issue by scottivell** [VeniVidiVici/givtcp-power-flow-card#69]
![CleanShot 2023-05-08 at 00 01 53@2x](https://user-images.githubusercontent.com/97510143/236706851-f3827f3f-f4b9-473f-9339-b76baca13aac.png)

When i toggle off single invertor, i can only add one to the options in visual editor. With two invertors the card doesn't work (without manual yaml)

**Comment by VeniVidiVici** [comment]
This should now be fixed in v0.5.0
