### ISSUE TITLE
Toggling "Details enabled" kills the power-flow-card

### ISSUE THREAD

**Issue by atifqdr** [VeniVidiVici/givtcp-power-flow-card#99]
Hi, Great Integration, using it daily, but when I enable the details (last tab in the config) the card disappears altogether! Tried various combinations but the "Details enabled" leads to the card disappearing from Lovelace!

**Comment by VeniVidiVici** [comment]
ok that looks like a bug, I am able to replicate it.

I'll take a look and get fix out, that might take a few days as I have a lot going on this weekend.

**Comment by atifqdr** [comment]
> ok that looks like a bug, I am able to replicate it.
> 
> I'll take a look and get fix out, that might take a few days as I have a lot going on this weekend.

Thank you
